name: corre_aqui
description: "Corre Aqui mobile app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.8
  # location: ^7.0.0
  http: ^1.2.2
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/maps/
