name: corre_aqui
description: "Corre Aqui mobile app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  flutter_local_notifications: ^19.0.0
  flutter_rating_stars: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.8
  # location: ^7.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  fonts:
    - family: RaelaGrotesque
      fonts:
        - asset: assets/fonts/RaelaGrotesque-Regular.ttf
        - asset: assets/fonts/RaelaGrotesque-Bold.ttf
          weight: 700
        - asset: assets/fonts/RaelaGrotesque-Thin.ttf
          style: italic
    - family: NeutralSans
      fonts:
        - asset: assets/fonts/NeutralSans-Regular.ttf
        - asset: assets/fonts/NeutralSans-Bold.ttf
          weight: 700

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/maps/
