// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6ahBEdDjGlZJlErU7_B9NqSGDIcy3_s',
    appId: '1:554206492965:web:86e45b1cc171bd940dc2cc',
    messagingSenderId: '554206492965',
    projectId: 'corre-aqui-aa9dd',
    authDomain: 'corre-aqui-aa9dd.firebaseapp.com',
    storageBucket: 'corre-aqui-aa9dd.firebasestorage.app',
    measurementId: 'G-EEPFGVB1ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9mNwNPhIpYlFknVBq0acgaa_6UPLCd4',
    appId: '1:554206492965:android:e0883f1dfb286f5b0dc2cc',
    messagingSenderId: '554206492965',
    projectId: 'corre-aqui-aa9dd',
    storageBucket: 'corre-aqui-aa9dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdPAL-23Q_8sTkR-RX1n3i381Kc_Yec4U',
    appId: '1:554206492965:ios:58a6c5295db3827e0dc2cc',
    messagingSenderId: '554206492965',
    projectId: 'corre-aqui-aa9dd',
    storageBucket: 'corre-aqui-aa9dd.firebasestorage.app',
    iosBundleId: 'com.correaqui.correAqui',
  );
}
